### ISSUE TITLE
function url support completion

### ISSUE THREAD

**Issue by huntharo** [awslabs/aws-lambda-web-adapter#160]
## Motivations
- The e2e tests have Function URL endpoint tests commented out
- The e2e SAM template is configuring a Function URL endpoint
- Function URLs are great (and I use them with AWS Lambda Web Adapter)!

## To-Do
- [ ] Confirm that we can flip the auth type from `AWS_IAM` to `NONE`: https://github.com/awslabs/aws-lambda-web-adapter/blob/73cb879ff22e9dc4fa1d0b31a84b7abdf3c06356/tests/e2e/fixtures/go-httpbin/template.yaml#L76-L77 - Rationale: the `ALB` is configured as `internet-facing` with a security group allowing `0.0.0.0/0` - So it seems we do not need to use auth for this ephemeral Function URL test
- [ ] Enable the E2Es for Function URLs
- [ ] Update the docs to note that they are supported

I can do the above if I get confirmation that we can turn of the auth.  If we can't turn off the auth I should be able to add the SigV4 signing in the Rust E2E tests when testing the Function URL endpoint.

**Comment by huntharo** [comment]
Oh that's no problem then to add the auth... I've done it for Node.js and it looks like there is an AWS Labs crate:

https://lib.rs/crates/aws-sig-auth

Here is my demo of signing the URLs for Node.js:

https://github.com/pwrdrvr/lambda-url-signing

I'll give this a try.  I think the only real challenge is making sure that we can configure which E2E targets need IAM signing... although I think signing the requests where we do not need the auth wouldn't actually break anything either.

**Comment by bnusunny** [comment]
We can extend the endpoint configuration to include such information.
